### ISSUE TITLE
Initals without space

### ISSUE THREAD

**Issue by kowach** [tamtamchik/namecase#10]
"J. D." leaves as it is, but "J.D." converts to "J.d."

**Comment by tamtamchik** [comment]
Can you please provide a full string example and the version that you use?
So far I can't reproduce the issue.

**Comment by peter279k** [comment]
I also cannot reproduce issue, and my code snippets are as follows:

```
>>> use \Tamtamchik\NameCase\Formatter;
>>> Formatter::nameCase('J.D.');
=> "J.D."
>>> Formatter::nameCase('J. D.');
=> "J. D."

```

**Comment by tamtamchik** [comment]
@kowach Can you please provide an example code along with the namespace version you use.

Thanks!

**Comment by kowach** [comment]
I'm not sure any more. Data was in the database.
I think I had "J. D." and "J.d." originally in DB and lazy mode was On (by default) so it did't changed it. 
It worked as documented :)

**Comment by tamtamchik** [comment]
Thank you for the feedback and for using namecase.
