### ISSUE TITLE
PHP Notice on empty string parameter

### ISSUE THREAD

**Issue by guenard** [tamtamchik/namecase#4]
If the string parameter supplied to nameCase is empty (`""`), PHP generates a notice with message _"Uninitialized string offset: 0"_ that comes from here: 

https://github.com/tamtamchik/namecase/blob/b4facc6022420bd1575d0c1d188c2ef870ef176b/src/Formatter.php#L122

It would be better to just check earlier that the string is empty and then return the empty string back instead of trying to access a character that does not exist.

**Comment by tamtamchik** [comment]
Fixed in version [1.0.3](
https://github.com/tamtamchik/namecase/tree/1.0.3)

**Comment by tamtamchik** [comment]
@guenard thank you for the report!

**Comment by guenard** [comment]
Wow you are fast @tamtamchik, great! Thank *you* for maintaining this repo.
