### ISSUE TITLE
Postnominal exceptions

### ISSUE THREAD

**Issue by arxeiss** [tamtamchik/namecase#7]
I don't understand most of post nominals and their origin. But is it possible to add exceptions option to not use some of them?

Reason is in Czech and other Slavic languages "Most" can be valid surname - meaning bridge. It is very rare but there are some occasions. Would it be possible to add post nominal exceptions? I don't want to disable all of them.

Btw. some of them are duplicated like BSc or MR etc

**Comment by tamtamchik** [comment]
I'll add an option to define post-nominals exceptions in a couple of days.
Thanks for the feedback!

**Comment by tamtamchik** [comment]
Released in [2.1.0](https://github.com/tamtamchik/namecase/releases/tag/2.1.0)

@arxeiss thank you for feedback and for waiting.
