### ISSUE TITLE
"MBE" is missing in POST_NOMINALS

### ISSUE THREAD

**Issue by pedanticantic** [tamtamchik/namecase#8]
Hi I just happened to notice that "MBE" is missing in the POST_NOMINALS constant in src/Formatter.php (it would be on line 86).

"OBE", "CBE", "KBE" and "DBE" are all present, so I assume it's just an oversight.

**Comment by tamtamchik** [comment]
Released in version [2.0.1](https://github.com/tamtamchik/namecase/releases/tag/2.0.1)

@pedanticantic thank you for your feedback!

**Comment by pedanticantic** [comment]
No worries. Thanks for making the change :-)
