### ISSUE TITLE
Missing \b 

### ISSUE THREAD

**Issue by arxeiss** [tamtamchik/namecase#9]
https://github.com/tamtamchik/namecase/blob/1128964fe17fdf46f44b5a3c05086e1fe92a44f0/src/Formatter.php#L51

There is missing end word boundary, this is causing problems with name Tereza or Tenerife etc.

**Comment by tamtamchik** [comment]
@arxeiss Wow! Indeed! Thank you!

**Comment by tamtamchik** [comment]
Fixed in [2.1.1](https://github.com/tamtamchik/namecase/releases/tag/2.1.1) and [1.0.6](https://github.com/tamtamchik/namecase/releases/tag/1.0.6)
